global:
  scrape_interval: 5s  # Intervalo de scraping predeterminado para todos los targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['10.0.1.10:9100']
